<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
		<SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
	  <Content Include="map.html">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="dotenv.net" Version="4.2.0" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4258.31" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Taxi.Core\Taxi.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update=".env">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>