// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Taxi.API.Server.Models;

public partial class ClientProfile
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int? DefaultPaymentMethodId { get; set; }

    public decimal Rating { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual PaymentMethod DefaultPaymentMethod { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual User User { get; set; }
}