// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Taxi.API.Server.Models;

public partial class Complaint
{
    public int Id { get; set; }

    public int AuthorUserId { get; set; }

    public int TargetUserId { get; set; }

    public int OrderId { get; set; }

    public int ComplaintTypeId { get; set; }

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public int StatusId { get; set; }

    public int ResolvedBy { get; set; }

    public DateTime ResolvedAt { get; set; }

    public string Resolution { get; set; }

    public virtual User AuthorUser { get; set; }

    public virtual ComplaintType ComplaintType { get; set; }

    public virtual Order Order { get; set; }

    public virtual User ResolvedByNavigation { get; set; }

    public virtual ComplaintStatus Status { get; set; }

    public virtual User TargetUser { get; set; }
}