// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Taxi.API.Server.Models;

public partial class DriverPayout
{
    public int Id { get; set; }

    public int DriverId { get; set; }

    public decimal Amount { get; set; }

    public DateTime? PaidAt { get; set; }

    public int? PaymentMethodId { get; set; }

    public virtual DriverProfile Driver { get; set; }

    public virtual PaymentMethod PaymentMethod { get; set; }
}