// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Taxi.API.Server.Models;

public partial class DriverDocumentType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<DriverDocument> DriverDocuments { get; set; } = new List<DriverDocument>();
}