// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Taxi.API.Server.Models;

public partial class DriverProfile
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string PassportSeries { get; set; }

    public string PassportNumber { get; set; }

    public string LicenseNumber { get; set; }

    public string LicenseCategories { get; set; }

    public int ExperienceYears { get; set; }

    public DateOnly DateNaima { get; set; }

    public bool IsActive { get; set; }

    public decimal SalaryRate { get; set; }

    public decimal Rating { get; set; }

    public virtual ICollection<DriverDocument> DriverDocuments { get; set; } = new List<DriverDocument>();

    public virtual ICollection<DriverPayout> DriverPayouts { get; set; } = new List<DriverPayout>();

    public virtual ICollection<Poezdka> Poezdkas { get; set; } = new List<Poezdka>();

    public virtual ICollection<Shift> Shifts { get; set; } = new List<Shift>();

    public virtual User User { get; set; }
}