// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Taxi.API.Server.Models;

public partial class Maintenance
{
    public int Id { get; set; }

    public int VehicleId { get; set; }

    public bool IsPlanned { get; set; }

    public DateOnly PlannedDate { get; set; }

    public DateOnly StartedAt { get; set; }

    public DateOnly? FinishedAt { get; set; }

    public string Description { get; set; }

    public decimal Cost { get; set; }

    public int ManagerId { get; set; }

    public string Result { get; set; }

    public bool? IsDone { get; set; }

    public virtual User Manager { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}