// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Taxi.API.Server.Models;

public partial class Order
{
    public int Id { get; set; }

    public int ClientId { get; set; }

    public int DispatcherId { get; set; }

    public int StatusId { get; set; }

    public int ClassId { get; set; }

    public int TariffId { get; set; }

    public string OtkudaAddress { get; set; }

    public string KudaAddress { get; set; }

    public int PassengersCount { get; set; }

    public string Comment { get; set; }

    public int PaymentMethodId { get; set; }

    public decimal PaymentAmount { get; set; }

    public DateTime PaidAt { get; set; }

    public bool IsPreliminary { get; set; }

    public DateTime ScheduledAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? CancelledAt { get; set; }

    public string CancelReason { get; set; }

    public virtual VehicleClass Class { get; set; }

    public virtual ClientProfile Client { get; set; }

    public virtual ICollection<Complaint> Complaints { get; set; } = new List<Complaint>();

    public virtual User Dispatcher { get; set; }

    public virtual PaymentMethod PaymentMethod { get; set; }

    public virtual ICollection<Poezdka> Poezdkas { get; set; } = new List<Poezdka>();

    public virtual OrderStatus Status { get; set; }

    public virtual Tariff Tariff { get; set; }
}