// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Taxi.API.Server.Models;

public partial class PaymentMethod
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<ClientProfile> ClientProfiles { get; set; } = new List<ClientProfile>();

    public virtual ICollection<DriverPayout> DriverPayouts { get; set; } = new List<DriverPayout>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}