// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Taxi.API.Server.Models;

public partial class Poezdka
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int DriverId { get; set; }

    public int VehicleId { get; set; }

    public DateTime StartedAt { get; set; }

    public DateTime? FinishedAt { get; set; }

    public decimal DriverEarning { get; set; }

    public virtual DriverProfile Driver { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<PoezdkaRating> PoezdkaRatings { get; set; } = new List<PoezdkaRating>();

    public virtual Vehicle Vehicle { get; set; }
}