// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Taxi.API.Server.Models;

public partial class PoezdkaRating
{
    public int Id { get; set; }

    public int PoezdkaId { get; set; }

    public int RatedByUserId { get; set; }

    public int RatedUserId { get; set; }

    public int Score { get; set; }

    public string Comment { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Poezdka Poezdka { get; set; }

    public virtual User RatedByUser { get; set; }

    public virtual User RatedUser { get; set; }
}