// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Taxi.API.Server.Models;

public partial class Shift
{
    public int Id { get; set; }

    public int DriverId { get; set; }

    public int VehicleId { get; set; }

    public DateTime OpenedAt { get; set; }

    public DateTime? ClosedAt { get; set; }

    public int? OrdersCount { get; set; }

    public int FuelStartLiters { get; set; }

    public int? FuelEndLiters { get; set; }

    public virtual DriverProfile Driver { get; set; }

    public virtual Vehicle Vehicle { get; set; }

    public virtual ICollection<Waybill> Waybills { get; set; } = new List<Waybill>();
}