// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Taxi.API.Server.Models;

public partial class Tariff
{
    public int Id { get; set; }

    public int ClassId { get; set; }

    public decimal BasePrice { get; set; }

    public decimal PricePerKm { get; set; }

    public decimal PricePerMinute { get; set; }

    public DateOnly ValidFrom { get; set; }

    public DateOnly ValidTo { get; set; }

    public bool? IsActive { get; set; }

    public virtual VehicleClass Class { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}