// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Taxi.API.Server.Models;

public partial class TaxiBaseContext : DbContext
{
    public TaxiBaseContext()
    {
    }

    public TaxiBaseContext(DbContextOptions<TaxiBaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ClientProfile> ClientProfiles { get; set; }

    public virtual DbSet<Complaint> Complaints { get; set; }

    public virtual DbSet<ComplaintStatus> ComplaintStatuses { get; set; }

    public virtual DbSet<ComplaintType> ComplaintTypes { get; set; }

    public virtual DbSet<DriverDocument> DriverDocuments { get; set; }

    public virtual DbSet<DriverDocumentType> DriverDocumentTypes { get; set; }

    public virtual DbSet<DriverPayout> DriverPayouts { get; set; }

    public virtual DbSet<DriverProfile> DriverProfiles { get; set; }

    public virtual DbSet<Maintenance> Maintenances { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderStatus> OrderStatuses { get; set; }

    public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }

    public virtual DbSet<Poezdka> Poezdkas { get; set; }

    public virtual DbSet<PoezdkaRating> PoezdkaRatings { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Shift> Shifts { get; set; }

    public virtual DbSet<Tariff> Tariffs { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Vehicle> Vehicles { get; set; }

    public virtual DbSet<VehicleClass> VehicleClasses { get; set; }

    public virtual DbSet<VehicleDocument> VehicleDocuments { get; set; }

    public virtual DbSet<VehicleDocumentType> VehicleDocumentTypes { get; set; }

    public virtual DbSet<Waybill> Waybills { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=TaxiBase;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ClientProfile>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__client_p__3213E83F7367C5B3");

            entity.ToTable("client_profile");

            entity.HasIndex(e => e.UserId, "UQ__client_p__B9BE370EA48A311D").IsUnique();

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.DefaultPaymentMethodId).HasColumnName("default_payment_method_id");
            entity.Property(e => e.Rating)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("rating");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.DefaultPaymentMethod).WithMany(p => p.ClientProfiles)
                .HasForeignKey(d => d.DefaultPaymentMethodId)
                .HasConstraintName("FK__client_pr__defau__6477ECF3");

            entity.HasOne(d => d.User).WithOne(p => p.ClientProfile)
                .HasForeignKey<ClientProfile>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__client_pr__user___6383C8BA");
        });

        modelBuilder.Entity<Complaint>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__complain__3213E83FCCFDBF69");

            entity.ToTable("complaint");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.AuthorUserId).HasColumnName("author_user_id");
            entity.Property(e => e.ComplaintTypeId).HasColumnName("complaint_type_id");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("description");
            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.Resolution)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("resolution");
            entity.Property(e => e.ResolvedAt)
                .HasColumnType("datetime")
                .HasColumnName("resolved_at");
            entity.Property(e => e.ResolvedBy).HasColumnName("resolved_by");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.TargetUserId).HasColumnName("target_user_id");

            entity.HasOne(d => d.AuthorUser).WithMany(p => p.ComplaintAuthorUsers)
                .HasForeignKey(d => d.AuthorUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__complaint__autho__00200768");

            entity.HasOne(d => d.ComplaintType).WithMany(p => p.Complaints)
                .HasForeignKey(d => d.ComplaintTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__complaint__compl__02FC7413");

            entity.HasOne(d => d.Order).WithMany(p => p.Complaints)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__complaint__order__02084FDA");

            entity.HasOne(d => d.ResolvedByNavigation).WithMany(p => p.ComplaintResolvedByNavigations)
                .HasForeignKey(d => d.ResolvedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__complaint__resol__04E4BC85");

            entity.HasOne(d => d.Status).WithMany(p => p.Complaints)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__complaint__statu__03F0984C");

            entity.HasOne(d => d.TargetUser).WithMany(p => p.ComplaintTargetUsers)
                .HasForeignKey(d => d.TargetUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__complaint__targe__01142BA1");
        });

        modelBuilder.Entity<ComplaintStatus>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__complain__3213E83F2AA2FACD");

            entity.ToTable("complaint_status");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
        });

        modelBuilder.Entity<ComplaintType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__complain__3213E83F15FC820E");

            entity.ToTable("complaint_type");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
        });

        modelBuilder.Entity<DriverDocument>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__driver_d__3213E83F799A1E2E");

            entity.ToTable("driver_document");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.DocNumber)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("doc_number");
            entity.Property(e => e.DocTypeId).HasColumnName("doc_type_id");
            entity.Property(e => e.DriverId).HasColumnName("driver_id");
            entity.Property(e => e.EndDate).HasColumnName("end_date");
            entity.Property(e => e.FilePath)
                .HasMaxLength(255)
                .HasColumnName("file_path");
            entity.Property(e => e.IsVerified).HasColumnName("is_verified");
            entity.Property(e => e.StartDate).HasColumnName("start_date");
            entity.Property(e => e.VerifiedAt)
                .HasColumnType("datetime")
                .HasColumnName("verified_at");
            entity.Property(e => e.VerifiedByUserId).HasColumnName("verified_by_user_id");

            entity.HasOne(d => d.DocType).WithMany(p => p.DriverDocuments)
                .HasForeignKey(d => d.DocTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__driver_do__doc_t__6754599E");

            entity.HasOne(d => d.Driver).WithMany(p => p.DriverDocuments)
                .HasForeignKey(d => d.DriverId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__driver_do__drive__66603565");

            entity.HasOne(d => d.VerifiedByUser).WithMany(p => p.DriverDocuments)
                .HasForeignKey(d => d.VerifiedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__driver_do__verif__68487DD7");
        });

        modelBuilder.Entity<DriverDocumentType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__driver_d__3213E83FC92B65E1");

            entity.ToTable("driver_document_type");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
        });

        modelBuilder.Entity<DriverPayout>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__driver_p__3213E83F1065EE0F");

            entity.ToTable("driver_payout");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Amount)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("amount");
            entity.Property(e => e.DriverId).HasColumnName("driver_id");
            entity.Property(e => e.PaidAt)
                .HasColumnType("datetime")
                .HasColumnName("paid_at");
            entity.Property(e => e.PaymentMethodId).HasColumnName("payment_method_id");

            entity.HasOne(d => d.Driver).WithMany(p => p.DriverPayouts)
                .HasForeignKey(d => d.DriverId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__driver_pa__drive__7E37BEF6");

            entity.HasOne(d => d.PaymentMethod).WithMany(p => p.DriverPayouts)
                .HasForeignKey(d => d.PaymentMethodId)
                .HasConstraintName("FK__driver_pa__payme__7F2BE32F");
        });

        modelBuilder.Entity<DriverProfile>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__driver_p__3213E83FAFEF1778");

            entity.ToTable("driver_profile");

            entity.HasIndex(e => e.UserId, "UQ__driver_p__B9BE370E68802EA4").IsUnique();

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.DateNaima).HasColumnName("date_naima");
            entity.Property(e => e.ExperienceYears).HasColumnName("experience_years");
            entity.Property(e => e.IsActive).HasColumnName("is_active");
            entity.Property(e => e.LicenseCategories)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("license_categories");
            entity.Property(e => e.LicenseNumber)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("license_number");
            entity.Property(e => e.PassportNumber)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("passport_number");
            entity.Property(e => e.PassportSeries)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("passport_series");
            entity.Property(e => e.Rating)
                .HasColumnType("decimal(3, 2)")
                .HasColumnName("rating");
            entity.Property(e => e.SalaryRate)
                .HasColumnType("decimal(15, 2)")
                .HasColumnName("salary_rate");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithOne(p => p.DriverProfile)
                .HasForeignKey<DriverProfile>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__driver_pr__user___656C112C");
        });

        modelBuilder.Entity<Maintenance>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__maintena__3213E83FC975D5FC");

            entity.ToTable("maintenance");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Cost)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("cost");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("description");
            entity.Property(e => e.FinishedAt).HasColumnName("finished_at");
            entity.Property(e => e.IsDone).HasColumnName("is_done");
            entity.Property(e => e.IsPlanned).HasColumnName("is_planned");
            entity.Property(e => e.ManagerId).HasColumnName("manager_id");
            entity.Property(e => e.PlannedDate).HasColumnName("planned_date");
            entity.Property(e => e.Result)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("result");
            entity.Property(e => e.StartedAt).HasColumnName("started_at");
            entity.Property(e => e.VehicleId).HasColumnName("vehicle_id");

            entity.HasOne(d => d.Manager).WithMany(p => p.Maintenances)
                .HasForeignKey(d => d.ManagerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__maintenan__manag__7D439ABD");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.Maintenances)
                .HasForeignKey(d => d.VehicleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__maintenan__vehic__7C4F7684");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__order__3213E83FA213E7AA");

            entity.ToTable("order");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.CancelReason)
                .HasMaxLength(255)
                .HasColumnName("cancel_reason");
            entity.Property(e => e.CancelledAt)
                .HasColumnType("datetime")
                .HasColumnName("cancelled_at");
            entity.Property(e => e.ClassId).HasColumnName("class_id");
            entity.Property(e => e.ClientId).HasColumnName("client_id");
            entity.Property(e => e.Comment)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("comment");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.DispatcherId).HasColumnName("dispatcher_id");
            entity.Property(e => e.IsPreliminary).HasColumnName("is_preliminary");
            entity.Property(e => e.KudaAddress)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("kuda_address");
            entity.Property(e => e.OtkudaAddress)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("otkuda_address");
            entity.Property(e => e.PaidAt)
                .HasColumnType("datetime")
                .HasColumnName("paid_at");
            entity.Property(e => e.PassengersCount).HasColumnName("passengers_count");
            entity.Property(e => e.PaymentAmount)
                .HasColumnType("decimal(16, 2)")
                .HasColumnName("payment_amount");
            entity.Property(e => e.PaymentMethodId).HasColumnName("payment_method_id");
            entity.Property(e => e.ScheduledAt)
                .HasColumnType("datetime")
                .HasColumnName("scheduled_at");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.TariffId).HasColumnName("tariff_id");

            entity.HasOne(d => d.Class).WithMany(p => p.Orders)
                .HasForeignKey(d => d.ClassId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__order__class_id__70DDC3D8");

            entity.HasOne(d => d.Client).WithMany(p => p.Orders)
                .HasForeignKey(d => d.ClientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__order__client_id__6E01572D");

            entity.HasOne(d => d.Dispatcher).WithMany(p => p.Orders)
                .HasForeignKey(d => d.DispatcherId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__order__dispatche__6EF57B66");

            entity.HasOne(d => d.PaymentMethod).WithMany(p => p.Orders)
                .HasForeignKey(d => d.PaymentMethodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__order__payment_m__72C60C4A");

            entity.HasOne(d => d.Status).WithMany(p => p.Orders)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__order__status_id__6FE99F9F");

            entity.HasOne(d => d.Tariff).WithMany(p => p.Orders)
                .HasForeignKey(d => d.TariffId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__order__tariff_id__71D1E811");
        });

        modelBuilder.Entity<OrderStatus>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__order_st__3213E83FEDC76E90");

            entity.ToTable("order_status");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
        });

        modelBuilder.Entity<PaymentMethod>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__payment___3213E83FCDEC6CF6");

            entity.ToTable("payment_method");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Poezdka>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__poezdka__3213E83F28674D93");

            entity.ToTable("poezdka");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.DriverEarning)
                .HasColumnType("decimal(16, 2)")
                .HasColumnName("driver_earning");
            entity.Property(e => e.DriverId).HasColumnName("driver_id");
            entity.Property(e => e.FinishedAt)
                .HasColumnType("datetime")
                .HasColumnName("finished_at");
            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.StartedAt)
                .HasColumnType("datetime")
                .HasColumnName("started_at");
            entity.Property(e => e.VehicleId).HasColumnName("vehicle_id");

            entity.HasOne(d => d.Driver).WithMany(p => p.Poezdkas)
                .HasForeignKey(d => d.DriverId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__poezdka__driver___74AE54BC");

            entity.HasOne(d => d.Order).WithMany(p => p.Poezdkas)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__poezdka__order_i__73BA3083");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.Poezdkas)
                .HasForeignKey(d => d.VehicleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__poezdka__vehicle__75A278F5");
        });

        modelBuilder.Entity<PoezdkaRating>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__poezdka___3213E83F00D026B3");

            entity.ToTable("poezdka_rating");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Comment)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("comment");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.PoezdkaId).HasColumnName("poezdka_id");
            entity.Property(e => e.RatedByUserId).HasColumnName("rated_by_user_id");
            entity.Property(e => e.RatedUserId).HasColumnName("rated_user_id");
            entity.Property(e => e.Score).HasColumnName("score");

            entity.HasOne(d => d.Poezdka).WithMany(p => p.PoezdkaRatings)
                .HasForeignKey(d => d.PoezdkaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__poezdka_r__poezd__76969D2E");

            entity.HasOne(d => d.RatedByUser).WithMany(p => p.PoezdkaRatingRatedByUsers)
                .HasForeignKey(d => d.RatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__poezdka_r__rated__778AC167");

            entity.HasOne(d => d.RatedUser).WithMany(p => p.PoezdkaRatingRatedUsers)
                .HasForeignKey(d => d.RatedUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__poezdka_r__rated__787EE5A0");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__role__3213E83F06DC5BF7");

            entity.ToTable("role");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Shift>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__shift__3213E83F06D7CC7C");

            entity.ToTable("shift");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.ClosedAt)
                .HasColumnType("datetime")
                .HasColumnName("closed_at");
            entity.Property(e => e.DriverId).HasColumnName("driver_id");
            entity.Property(e => e.FuelEndLiters).HasColumnName("fuel_end_liters");
            entity.Property(e => e.FuelStartLiters).HasColumnName("fuel_start_liters");
            entity.Property(e => e.OpenedAt)
                .HasColumnType("datetime")
                .HasColumnName("opened_at");
            entity.Property(e => e.OrdersCount).HasColumnName("orders_count");
            entity.Property(e => e.VehicleId).HasColumnName("vehicle_id");

            entity.HasOne(d => d.Driver).WithMany(p => p.Shifts)
                .HasForeignKey(d => d.DriverId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__shift__driver_id__797309D9");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.Shifts)
                .HasForeignKey(d => d.VehicleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__shift__vehicle_i__7A672E12");
        });

        modelBuilder.Entity<Tariff>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tariff__3213E83F9CB7728D");

            entity.ToTable("tariff");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.BasePrice)
                .HasColumnType("decimal(16, 2)")
                .HasColumnName("base_price");
            entity.Property(e => e.ClassId).HasColumnName("class_id");
            entity.Property(e => e.IsActive).HasColumnName("is_active");
            entity.Property(e => e.PricePerKm)
                .HasColumnType("decimal(16, 2)")
                .HasColumnName("price_per_km");
            entity.Property(e => e.PricePerMinute)
                .HasColumnType("decimal(16, 2)")
                .HasColumnName("price_per_minute");
            entity.Property(e => e.ValidFrom).HasColumnName("valid_from");
            entity.Property(e => e.ValidTo).HasColumnName("valid_to");

            entity.HasOne(d => d.Class).WithMany(p => p.Tariffs)
                .HasForeignKey(d => d.ClassId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tariff__class_id__6D0D32F4");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__user__3213E83FB87D7692");

            entity.ToTable("user");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("email");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("first_name");
            entity.Property(e => e.IsActive).HasColumnName("is_active");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("last_name");
            entity.Property(e => e.Login)
                .IsRequired()
                .HasColumnName("login");
            entity.Property(e => e.MiddleName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("middle_name");
            entity.Property(e => e.PasswordHashe)
                .IsRequired()
                .HasColumnName("passwordHashe");
            entity.Property(e => e.RoleId).HasColumnName("role_id");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__user__role_id__628FA481");
        });

        modelBuilder.Entity<Vehicle>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__vehicle__3213E83FD79BFBC6");

            entity.ToTable("vehicle");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Brand)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("brand");
            entity.Property(e => e.ClassId).HasColumnName("class_id");
            entity.Property(e => e.GovNumber)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("gov_number");
            entity.Property(e => e.IsActive).HasColumnName("is_active");
            entity.Property(e => e.Model)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("model");
            entity.Property(e => e.Year).HasColumnName("year");

            entity.HasOne(d => d.Class).WithMany(p => p.Vehicles)
                .HasForeignKey(d => d.ClassId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__vehicle__class_i__693CA210");
        });

        modelBuilder.Entity<VehicleClass>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__vehicle___3213E83F97D7BE10");

            entity.ToTable("vehicle_class");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
        });

        modelBuilder.Entity<VehicleDocument>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__vehicle___3213E83F4D143164");

            entity.ToTable("vehicle_document");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.DocNumber)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("doc_number");
            entity.Property(e => e.DocTypeId).HasColumnName("doc_type_id");
            entity.Property(e => e.EndDate).HasColumnName("end_date");
            entity.Property(e => e.FilePath)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("file_path");
            entity.Property(e => e.IsVerified).HasColumnName("is_verified");
            entity.Property(e => e.StartDate).HasColumnName("start_date");
            entity.Property(e => e.VehicleId).HasColumnName("vehicle_id");
            entity.Property(e => e.VerifiedAt)
                .HasColumnType("datetime")
                .HasColumnName("verified_at");
            entity.Property(e => e.VerifiedByUserId).HasColumnName("verified_by_user_id");

            entity.HasOne(d => d.DocType).WithMany(p => p.VehicleDocuments)
                .HasForeignKey(d => d.DocTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__vehicle_d__doc_t__6B24EA82");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.VehicleDocuments)
                .HasForeignKey(d => d.VehicleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__vehicle_d__vehic__6A30C649");

            entity.HasOne(d => d.VerifiedByUser).WithMany(p => p.VehicleDocuments)
                .HasForeignKey(d => d.VerifiedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__vehicle_d__verif__6C190EBB");
        });

        modelBuilder.Entity<VehicleDocumentType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__vehicle___3213E83F42E10416");

            entity.ToTable("vehicle_document_type");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Waybill>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__waybill__3213E83FDEC7F76A");

            entity.ToTable("waybill");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.DepartureTime)
                .HasColumnType("datetime")
                .HasColumnName("departure_time");
            entity.Property(e => e.MedcheckAt)
                .HasColumnType("datetime")
                .HasColumnName("medcheck_at");
            entity.Property(e => e.MedcheckComment)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("medcheck_comment");
            entity.Property(e => e.MedcheckResult)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("medcheck_result");
            entity.Property(e => e.Number)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("number");
            entity.Property(e => e.ReturnTime)
                .HasColumnType("datetime")
                .HasColumnName("return_time");
            entity.Property(e => e.ShiftId).HasColumnName("shift_id");
            entity.Property(e => e.StartedAt).HasColumnName("started_at");
            entity.Property(e => e.TechComment)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("tech_comment");
            entity.Property(e => e.TechStateOk).HasColumnName("tech_state_ok");

            entity.HasOne(d => d.Shift).WithMany(p => p.Waybills)
                .HasForeignKey(d => d.ShiftId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__waybill__shift_i__7B5B524B");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}