// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Taxi.API.Server.Models;

public partial class User
{
    public int Id { get; set; }

    public string Login { get; set; }

    public int RoleId { get; set; }

    public string PasswordHashe { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string Email { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsActive { get; set; }

    public virtual ClientProfile ClientProfile { get; set; }

    public virtual ICollection<Complaint> ComplaintAuthorUsers { get; set; } = new List<Complaint>();

    public virtual ICollection<Complaint> ComplaintResolvedByNavigations { get; set; } = new List<Complaint>();

    public virtual ICollection<Complaint> ComplaintTargetUsers { get; set; } = new List<Complaint>();

    public virtual ICollection<DriverDocument> DriverDocuments { get; set; } = new List<DriverDocument>();

    public virtual DriverProfile DriverProfile { get; set; }

    public virtual ICollection<Maintenance> Maintenances { get; set; } = new List<Maintenance>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<PoezdkaRating> PoezdkaRatingRatedByUsers { get; set; } = new List<PoezdkaRating>();

    public virtual ICollection<PoezdkaRating> PoezdkaRatingRatedUsers { get; set; } = new List<PoezdkaRating>();

    public virtual Role Role { get; set; }

    public virtual ICollection<VehicleDocument> VehicleDocuments { get; set; } = new List<VehicleDocument>();
}