// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Taxi.API.Server.Models;

public partial class Vehicle
{
    public int Id { get; set; }

    public string GovNumber { get; set; }

    public string Model { get; set; }

    public string Brand { get; set; }

    public int ClassId { get; set; }

    public int Year { get; set; }

    public bool IsActive { get; set; }

    public virtual VehicleClass Class { get; set; }

    public virtual ICollection<Maintenance> Maintenances { get; set; } = new List<Maintenance>();

    public virtual ICollection<Poezdka> Poezdkas { get; set; } = new List<Poezdka>();

    public virtual ICollection<Shift> Shifts { get; set; } = new List<Shift>();

    public virtual ICollection<VehicleDocument> VehicleDocuments { get; set; } = new List<VehicleDocument>();
}