// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Taxi.API.Server.Models;

public partial class VehicleDocument
{
    public int Id { get; set; }

    public int VehicleId { get; set; }

    public int DocTypeId { get; set; }

    public string DocNumber { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public string FilePath { get; set; }

    public bool IsVerified { get; set; }

    public int VerifiedByUserId { get; set; }

    public DateTime VerifiedAt { get; set; }

    public virtual VehicleDocumentType DocType { get; set; }

    public virtual Vehicle Vehicle { get; set; }

    public virtual User VerifiedByUser { get; set; }
}