// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Taxi.API.Server.Models;

public partial class Waybill
{
    public int Id { get; set; }

    public int ShiftId { get; set; }

    public string Number { get; set; }

    public DateOnly StartedAt { get; set; }

    public DateTime? DepartureTime { get; set; }

    public DateTime? ReturnTime { get; set; }

    public bool TechStateOk { get; set; }

    public string TechComment { get; set; }

    public DateTime MedcheckAt { get; set; }

    public string MedcheckResult { get; set; }

    public string MedcheckComment { get; set; }

    public virtual Shift Shift { get; set; }
}